print("\"git init\" used to create a git repository")
print("There are local area & staging area")
print("Local area is the area that located at the git init location")
print("Staging area is the area that tracked")
print("\"git status\" used to check status of this git repository")
print("\"git add <filename>\" used to add file to the staging area")
print("\"git rm --cached <filename>\" used to remove file from the staging area")
print("\"git branch\" used to show the branches those we have")
print("\"git merge <branchname>\" used to merge current branch with the selected branch")
print("\"git checkout -b <branchname>\" used to create a new branch")
print("We may do different action to same file in different branches")
print("If we want go back to the original file, then switched back to the branch")

print("\"git pull\" used to pull the code from the remote repository")

print("THE END")
